AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 7
          Status: Enabled

  VectorBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 7
          Status: Enabled

  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: "{\"OPENAI_API_KEY\":\"placeholder\"}"

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - x86_64
      CodeUri: upload/
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref SourceBucket
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /upload
            Method: post
      Handler: app.lambda_handler
      Policies:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Runtime: python3.11
      Timeout: 16

  VectorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./vector
    Properties:
      Architectures:
      - x86_64
      Environment:
        Variables:
          VECTOR_BUCKET: !Ref VectorBucket
      Events:
        S3:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
      MemorySize: 256
      PackageType: Image
      Policies:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Timeout: 32

  ChatFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./chat
    Properties:
      Architectures:
      - x86_64
      Environment:
        Variables:
          SECRET_ARN: !Ref Secret
          VECTOR_BUCKET: !Ref VectorBucket
      Events:
        Chat:
          Type: Api
          Properties:
            Path: /chat
            Method: post
      PackageType: Image
      Policies:
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Timeout: 16

Outputs:
  UploadURL:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"
  ChatURL:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chat/"
